ARG DOCKER_ENVIRONMENT
FROM idk:latest

ENV PYTHONUNBUFFERED True
ENV APP_HOME /app

ARG BRANCH
ARG PIP_TOKEN

WORKDIR $APP_HOME
COPY . ./

RUN pip3 install -r requirements.txt

EXPOSE 8080
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]
# CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "--bind", ":8080", "--workers", "1", "--threads", "8", "--timeout", "0", "api:app"]