name: Build Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test'
        required: false
        type: boolean


jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image to Amazon ECR
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          053467565326.dkr.ecr.us-east-1.amazonaws.com/columni:${{ github.event.pull_request.head.ref == null && 'v' || 'dev-v' }}${{ github.run_number }}
          053467565326.dkr.ecr.us-east-1.amazonaws.com/columni:${{ github.event.pull_request.head.ref == null && 'latest' || 'dev' }}

    # - name: Deploy to EC2
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #     # Add your deployment script here
